/* 
 * UserVoice API
 *
 * A RESTful API to interface with UserVoice's feedback system. Online documentation available here: https://developer.uservoice.com/docs/api/v2/reference/.
 *
 * OpenAPI spec version: 2.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;

namespace UserVoiceSdk.Models
{
    /// <summary>
    /// EmailAliasLinks
    /// </summary>
    [DataContract]
    public partial class EmailAliasLinks :  IEquatable<EmailAliasLinks>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="EmailAliasLinks" /> class.
        /// </summary>
        /// <param name="CustomEmailDomain">CustomEmailDomain.</param>
        public EmailAliasLinks(long? CustomEmailDomain = null)
        {
            this.CustomEmailDomain = CustomEmailDomain;
        }
        
        /// <summary>
        /// Gets or Sets CustomEmailDomain
        /// </summary>
        [DataMember(Name="custom_email_domain", EmitDefaultValue=false)]
        public long? CustomEmailDomain { get; set; }
        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class EmailAliasLinks {\n");
            sb.Append("  CustomEmailDomain: ").Append(CustomEmailDomain).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            // credit: http://stackoverflow.com/a/10454552/677735
            return this.Equals(obj as EmailAliasLinks);
        }

        /// <summary>
        /// Returns true if EmailAliasLinks instances are equal
        /// </summary>
        /// <param name="other">Instance of EmailAliasLinks to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(EmailAliasLinks other)
        {
            // credit: http://stackoverflow.com/a/10454552/677735
            if (other == null)
                return false;

            return 
                (
                    this.CustomEmailDomain == other.CustomEmailDomain ||
                    this.CustomEmailDomain != null &&
                    this.CustomEmailDomain.Equals(other.CustomEmailDomain)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            // credit: http://stackoverflow.com/a/263416/677735
            unchecked // Overflow is fine, just wrap
            {
                int hash = 41;
                // Suitable nullity checks etc, of course :)
                if (this.CustomEmailDomain != null)
                    hash = hash * 59 + this.CustomEmailDomain.GetHashCode();
                return hash;
            }
        }

        public IEnumerable<ValidationResult> Validate(ValidationContext validationContext)
        { 
            yield break;
        }
    }

}
