/* 
 * UserVoice API
 *
 * A RESTful API to interface with UserVoice's feedback system. Online documentation available here: https://developer.uservoice.com/docs/api/v2/reference/.
 *
 * OpenAPI spec version: 2.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;

namespace UserVoiceSdk.Models
{
    /// <summary>
    /// FeedbackLinks
    /// </summary>
    [DataContract]
    public partial class FeedbackLinks :  IEquatable<FeedbackLinks>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="FeedbackLinks" /> class.
        /// </summary>
        /// <param name="CreatedBy">CreatedBy.</param>
        /// <param name="Suggestion">Suggestion.</param>
        /// <param name="Supporter">Supporter.</param>
        /// <param name="Ticket">Ticket.</param>
        /// <param name="UpdatedBy">UpdatedBy.</param>
        /// <param name="User">User.</param>
        public FeedbackLinks(long? CreatedBy = null, long? Suggestion = null, long? Supporter = null, long? Ticket = null, long? UpdatedBy = null, long? User = null)
        {
            this.CreatedBy = CreatedBy;
            this.Suggestion = Suggestion;
            this.Supporter = Supporter;
            this.Ticket = Ticket;
            this.UpdatedBy = UpdatedBy;
            this.User = User;
        }
        
        /// <summary>
        /// Gets or Sets CreatedBy
        /// </summary>
        [DataMember(Name="created_by", EmitDefaultValue=false)]
        public long? CreatedBy { get; set; }
        /// <summary>
        /// Gets or Sets Suggestion
        /// </summary>
        [DataMember(Name="suggestion", EmitDefaultValue=false)]
        public long? Suggestion { get; set; }
        /// <summary>
        /// Gets or Sets Supporter
        /// </summary>
        [DataMember(Name="supporter", EmitDefaultValue=false)]
        public long? Supporter { get; set; }
        /// <summary>
        /// Gets or Sets Ticket
        /// </summary>
        [DataMember(Name="ticket", EmitDefaultValue=false)]
        public long? Ticket { get; set; }
        /// <summary>
        /// Gets or Sets UpdatedBy
        /// </summary>
        [DataMember(Name="updated_by", EmitDefaultValue=false)]
        public long? UpdatedBy { get; set; }
        /// <summary>
        /// Gets or Sets User
        /// </summary>
        [DataMember(Name="user", EmitDefaultValue=false)]
        public long? User { get; set; }
        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class FeedbackLinks {\n");
            sb.Append("  CreatedBy: ").Append(CreatedBy).Append("\n");
            sb.Append("  Suggestion: ").Append(Suggestion).Append("\n");
            sb.Append("  Supporter: ").Append(Supporter).Append("\n");
            sb.Append("  Ticket: ").Append(Ticket).Append("\n");
            sb.Append("  UpdatedBy: ").Append(UpdatedBy).Append("\n");
            sb.Append("  User: ").Append(User).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            // credit: http://stackoverflow.com/a/10454552/677735
            return this.Equals(obj as FeedbackLinks);
        }

        /// <summary>
        /// Returns true if FeedbackLinks instances are equal
        /// </summary>
        /// <param name="other">Instance of FeedbackLinks to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(FeedbackLinks other)
        {
            // credit: http://stackoverflow.com/a/10454552/677735
            if (other == null)
                return false;

            return 
                (
                    this.CreatedBy == other.CreatedBy ||
                    this.CreatedBy != null &&
                    this.CreatedBy.Equals(other.CreatedBy)
                ) && 
                (
                    this.Suggestion == other.Suggestion ||
                    this.Suggestion != null &&
                    this.Suggestion.Equals(other.Suggestion)
                ) && 
                (
                    this.Supporter == other.Supporter ||
                    this.Supporter != null &&
                    this.Supporter.Equals(other.Supporter)
                ) && 
                (
                    this.Ticket == other.Ticket ||
                    this.Ticket != null &&
                    this.Ticket.Equals(other.Ticket)
                ) && 
                (
                    this.UpdatedBy == other.UpdatedBy ||
                    this.UpdatedBy != null &&
                    this.UpdatedBy.Equals(other.UpdatedBy)
                ) && 
                (
                    this.User == other.User ||
                    this.User != null &&
                    this.User.Equals(other.User)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            // credit: http://stackoverflow.com/a/263416/677735
            unchecked // Overflow is fine, just wrap
            {
                int hash = 41;
                // Suitable nullity checks etc, of course :)
                if (this.CreatedBy != null)
                    hash = hash * 59 + this.CreatedBy.GetHashCode();
                if (this.Suggestion != null)
                    hash = hash * 59 + this.Suggestion.GetHashCode();
                if (this.Supporter != null)
                    hash = hash * 59 + this.Supporter.GetHashCode();
                if (this.Ticket != null)
                    hash = hash * 59 + this.Ticket.GetHashCode();
                if (this.UpdatedBy != null)
                    hash = hash * 59 + this.UpdatedBy.GetHashCode();
                if (this.User != null)
                    hash = hash * 59 + this.User.GetHashCode();
                return hash;
            }
        }

        public IEnumerable<ValidationResult> Validate(ValidationContext validationContext)
        { 
            yield break;
        }
    }

}
