/* 
 * UserVoice API
 *
 * No descripton provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;

namespace UservoiceSDK.Models
{
    /// <summary>
    /// SuggestionActivityEntryResponsePaginated
    /// </summary>
    [DataContract]
    public partial class SuggestionActivityEntryResponsePaginated :  IEquatable<SuggestionActivityEntryResponsePaginated>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="SuggestionActivityEntryResponsePaginated" /> class.
        /// </summary>
        /// <param name="Categories">Categories.</param>
        /// <param name="Comments">Comments.</param>
        /// <param name="Feedback">Feedback.</param>
        /// <param name="Forums">Forums.</param>
        /// <param name="Messages">Messages.</param>
        /// <param name="Notes">Notes.</param>
        /// <param name="StatusUpdates">StatusUpdates.</param>
        /// <param name="SuggestionActivityEntries">SuggestionActivityEntries.</param>
        /// <param name="Suggestions">Suggestions.</param>
        /// <param name="Tickets">Tickets.</param>
        /// <param name="Users">Users.</param>
        /// <param name="Pagination">Pagination.</param>
        public SuggestionActivityEntryResponsePaginated(List<Category> Categories = null, List<Comment> Comments = null, List<Feedback> Feedback = null, List<Forum> Forums = null, List<Message> Messages = null, List<Note> Notes = null, List<StatusUpdate> StatusUpdates = null, List<SuggestionActivityEntry> SuggestionActivityEntries = null, List<Suggestion> Suggestions = null, List<Ticket> Tickets = null, List<User> Users = null, Pagination Pagination = null)
        {
            this.Categories = Categories;
            this.Comments = Comments;
            this.Feedback = Feedback;
            this.Forums = Forums;
            this.Messages = Messages;
            this.Notes = Notes;
            this.StatusUpdates = StatusUpdates;
            this.SuggestionActivityEntries = SuggestionActivityEntries;
            this.Suggestions = Suggestions;
            this.Tickets = Tickets;
            this.Users = Users;
            this.Pagination = Pagination;
        }
        
        /// <summary>
        /// Gets or Sets Categories
        /// </summary>
        [DataMember(Name="categories", EmitDefaultValue=false)]
        public List<Category> Categories { get; set; }
        /// <summary>
        /// Gets or Sets Comments
        /// </summary>
        [DataMember(Name="comments", EmitDefaultValue=false)]
        public List<Comment> Comments { get; set; }
        /// <summary>
        /// Gets or Sets Feedback
        /// </summary>
        [DataMember(Name="feedback", EmitDefaultValue=false)]
        public List<Feedback> Feedback { get; set; }
        /// <summary>
        /// Gets or Sets Forums
        /// </summary>
        [DataMember(Name="forums", EmitDefaultValue=false)]
        public List<Forum> Forums { get; set; }
        /// <summary>
        /// Gets or Sets Messages
        /// </summary>
        [DataMember(Name="messages", EmitDefaultValue=false)]
        public List<Message> Messages { get; set; }
        /// <summary>
        /// Gets or Sets Notes
        /// </summary>
        [DataMember(Name="notes", EmitDefaultValue=false)]
        public List<Note> Notes { get; set; }
        /// <summary>
        /// Gets or Sets StatusUpdates
        /// </summary>
        [DataMember(Name="status_updates", EmitDefaultValue=false)]
        public List<StatusUpdate> StatusUpdates { get; set; }
        /// <summary>
        /// Gets or Sets SuggestionActivityEntries
        /// </summary>
        [DataMember(Name="suggestion_activity_entries", EmitDefaultValue=false)]
        public List<SuggestionActivityEntry> SuggestionActivityEntries { get; set; }
        /// <summary>
        /// Gets or Sets Suggestions
        /// </summary>
        [DataMember(Name="suggestions", EmitDefaultValue=false)]
        public List<Suggestion> Suggestions { get; set; }
        /// <summary>
        /// Gets or Sets Tickets
        /// </summary>
        [DataMember(Name="tickets", EmitDefaultValue=false)]
        public List<Ticket> Tickets { get; set; }
        /// <summary>
        /// Gets or Sets Users
        /// </summary>
        [DataMember(Name="users", EmitDefaultValue=false)]
        public List<User> Users { get; set; }
        /// <summary>
        /// Gets or Sets Pagination
        /// </summary>
        [DataMember(Name="pagination", EmitDefaultValue=false)]
        public Pagination Pagination { get; set; }
        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class SuggestionActivityEntryResponsePaginated {\n");
            sb.Append("  Categories: ").Append(Categories).Append("\n");
            sb.Append("  Comments: ").Append(Comments).Append("\n");
            sb.Append("  Feedback: ").Append(Feedback).Append("\n");
            sb.Append("  Forums: ").Append(Forums).Append("\n");
            sb.Append("  Messages: ").Append(Messages).Append("\n");
            sb.Append("  Notes: ").Append(Notes).Append("\n");
            sb.Append("  StatusUpdates: ").Append(StatusUpdates).Append("\n");
            sb.Append("  SuggestionActivityEntries: ").Append(SuggestionActivityEntries).Append("\n");
            sb.Append("  Suggestions: ").Append(Suggestions).Append("\n");
            sb.Append("  Tickets: ").Append(Tickets).Append("\n");
            sb.Append("  Users: ").Append(Users).Append("\n");
            sb.Append("  Pagination: ").Append(Pagination).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            // credit: http://stackoverflow.com/a/10454552/677735
            return this.Equals(obj as SuggestionActivityEntryResponsePaginated);
        }

        /// <summary>
        /// Returns true if SuggestionActivityEntryResponsePaginated instances are equal
        /// </summary>
        /// <param name="other">Instance of SuggestionActivityEntryResponsePaginated to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(SuggestionActivityEntryResponsePaginated other)
        {
            // credit: http://stackoverflow.com/a/10454552/677735
            if (other == null)
                return false;

            return 
                (
                    this.Categories == other.Categories ||
                    this.Categories != null &&
                    this.Categories.SequenceEqual(other.Categories)
                ) && 
                (
                    this.Comments == other.Comments ||
                    this.Comments != null &&
                    this.Comments.SequenceEqual(other.Comments)
                ) && 
                (
                    this.Feedback == other.Feedback ||
                    this.Feedback != null &&
                    this.Feedback.SequenceEqual(other.Feedback)
                ) && 
                (
                    this.Forums == other.Forums ||
                    this.Forums != null &&
                    this.Forums.SequenceEqual(other.Forums)
                ) && 
                (
                    this.Messages == other.Messages ||
                    this.Messages != null &&
                    this.Messages.SequenceEqual(other.Messages)
                ) && 
                (
                    this.Notes == other.Notes ||
                    this.Notes != null &&
                    this.Notes.SequenceEqual(other.Notes)
                ) && 
                (
                    this.StatusUpdates == other.StatusUpdates ||
                    this.StatusUpdates != null &&
                    this.StatusUpdates.SequenceEqual(other.StatusUpdates)
                ) && 
                (
                    this.SuggestionActivityEntries == other.SuggestionActivityEntries ||
                    this.SuggestionActivityEntries != null &&
                    this.SuggestionActivityEntries.SequenceEqual(other.SuggestionActivityEntries)
                ) && 
                (
                    this.Suggestions == other.Suggestions ||
                    this.Suggestions != null &&
                    this.Suggestions.SequenceEqual(other.Suggestions)
                ) && 
                (
                    this.Tickets == other.Tickets ||
                    this.Tickets != null &&
                    this.Tickets.SequenceEqual(other.Tickets)
                ) && 
                (
                    this.Users == other.Users ||
                    this.Users != null &&
                    this.Users.SequenceEqual(other.Users)
                ) && 
                (
                    this.Pagination == other.Pagination ||
                    this.Pagination != null &&
                    this.Pagination.Equals(other.Pagination)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            // credit: http://stackoverflow.com/a/263416/677735
            unchecked // Overflow is fine, just wrap
            {
                int hash = 41;
                // Suitable nullity checks etc, of course :)
                if (this.Categories != null)
                    hash = hash * 59 + this.Categories.GetHashCode();
                if (this.Comments != null)
                    hash = hash * 59 + this.Comments.GetHashCode();
                if (this.Feedback != null)
                    hash = hash * 59 + this.Feedback.GetHashCode();
                if (this.Forums != null)
                    hash = hash * 59 + this.Forums.GetHashCode();
                if (this.Messages != null)
                    hash = hash * 59 + this.Messages.GetHashCode();
                if (this.Notes != null)
                    hash = hash * 59 + this.Notes.GetHashCode();
                if (this.StatusUpdates != null)
                    hash = hash * 59 + this.StatusUpdates.GetHashCode();
                if (this.SuggestionActivityEntries != null)
                    hash = hash * 59 + this.SuggestionActivityEntries.GetHashCode();
                if (this.Suggestions != null)
                    hash = hash * 59 + this.Suggestions.GetHashCode();
                if (this.Tickets != null)
                    hash = hash * 59 + this.Tickets.GetHashCode();
                if (this.Users != null)
                    hash = hash * 59 + this.Users.GetHashCode();
                if (this.Pagination != null)
                    hash = hash * 59 + this.Pagination.GetHashCode();
                return hash;
            }
        }

        public IEnumerable<ValidationResult> Validate(ValidationContext validationContext)
        { 
            yield break;
        }
    }

}
