/* 
 * UserVoice API
 *
 * No descripton provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using UservoiceSDK.Api;
using UservoiceSDK.Models;
using UservoiceSDK.Client;
using System.Reflection;

namespace UservoiceSDK.Test
{
    /// <summary>
    ///  Class for testing AttachmentResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class AttachmentResponseTests
    {
        // TODO uncomment below to declare an instance variable for AttachmentResponse
        //private AttachmentResponse instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of AttachmentResponse
            //instance = new AttachmentResponse();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of AttachmentResponse
        /// </summary>
        [Test]
        public void AttachmentResponseInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" AttachmentResponse
            //Assert.IsInstanceOfType<AttachmentResponse> (instance, "variable 'instance' is a AttachmentResponse");
        }

        /// <summary>
        /// Test the property 'Attachments'
        /// </summary>
        [Test]
        public void AttachmentsTest()
        {
            // TODO unit test for the property 'Attachments'
        }
        /// <summary>
        /// Test the property 'Notes'
        /// </summary>
        [Test]
        public void NotesTest()
        {
            // TODO unit test for the property 'Notes'
        }
        /// <summary>
        /// Test the property 'Suggestions'
        /// </summary>
        [Test]
        public void SuggestionsTest()
        {
            // TODO unit test for the property 'Suggestions'
        }

    }

}
