/* 
 * UserVoice API
 *
 * No descripton provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using UservoiceSDK.Api;
using UservoiceSDK.Models;
using UservoiceSDK.Client;
using System.Reflection;

namespace UservoiceSDK.Test
{
    /// <summary>
    ///  Class for testing CommentResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class CommentResponseTests
    {
        // TODO uncomment below to declare an instance variable for CommentResponse
        //private CommentResponse instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of CommentResponse
            //instance = new CommentResponse();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of CommentResponse
        /// </summary>
        [Test]
        public void CommentResponseInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" CommentResponse
            //Assert.IsInstanceOfType<CommentResponse> (instance, "variable 'instance' is a CommentResponse");
        }

        /// <summary>
        /// Test the property 'Comments'
        /// </summary>
        [Test]
        public void CommentsTest()
        {
            // TODO unit test for the property 'Comments'
        }
        /// <summary>
        /// Test the property 'Suggestions'
        /// </summary>
        [Test]
        public void SuggestionsTest()
        {
            // TODO unit test for the property 'Suggestions'
        }
        /// <summary>
        /// Test the property 'Users'
        /// </summary>
        [Test]
        public void UsersTest()
        {
            // TODO unit test for the property 'Users'
        }

    }

}
