/* 
 * UserVoice API
 *
 * No descripton provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using UservoiceSDK.Api;
using UservoiceSDK.Models;
using UservoiceSDK.Client;
using System.Reflection;

namespace UservoiceSDK.Test
{
    /// <summary>
    ///  Class for testing ForumLinks
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class ForumLinksTests
    {
        // TODO uncomment below to declare an instance variable for ForumLinks
        //private ForumLinks instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of ForumLinks
            //instance = new ForumLinks();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of ForumLinks
        /// </summary>
        [Test]
        public void ForumLinksInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" ForumLinks
            //Assert.IsInstanceOfType<ForumLinks> (instance, "variable 'instance' is a ForumLinks");
        }

        /// <summary>
        /// Test the property 'UpdatedBy'
        /// </summary>
        [Test]
        public void UpdatedByTest()
        {
            // TODO unit test for the property 'UpdatedBy'
        }

    }

}
