/* 
 * UserVoice API
 *
 * No descripton provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using UservoiceSDK.Api;
using UservoiceSDK.Models;
using UservoiceSDK.Client;
using System.Reflection;

namespace UservoiceSDK.Test
{
    /// <summary>
    ///  Class for testing Status
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class StatusTests
    {
        // TODO uncomment below to declare an instance variable for Status
        //private Status instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of Status
            //instance = new Status();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of Status
        /// </summary>
        [Test]
        public void StatusInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" Status
            //Assert.IsInstanceOfType<Status> (instance, "variable 'instance' is a Status");
        }

        /// <summary>
        /// Test the property 'AllowComments'
        /// </summary>
        [Test]
        public void AllowCommentsTest()
        {
            // TODO unit test for the property 'AllowComments'
        }
        /// <summary>
        /// Test the property 'CreatedAt'
        /// </summary>
        [Test]
        public void CreatedAtTest()
        {
            // TODO unit test for the property 'CreatedAt'
        }
        /// <summary>
        /// Test the property 'HexColor'
        /// </summary>
        [Test]
        public void HexColorTest()
        {
            // TODO unit test for the property 'HexColor'
        }
        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Test]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }
        /// <summary>
        /// Test the property 'IsOpen'
        /// </summary>
        [Test]
        public void IsOpenTest()
        {
            // TODO unit test for the property 'IsOpen'
        }
        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Test]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }
        /// <summary>
        /// Test the property 'Position'
        /// </summary>
        [Test]
        public void PositionTest()
        {
            // TODO unit test for the property 'Position'
        }
        /// <summary>
        /// Test the property 'UpdatedAt'
        /// </summary>
        [Test]
        public void UpdatedAtTest()
        {
            // TODO unit test for the property 'UpdatedAt'
        }

    }

}
