/* 
 * UserVoice API
 *
 * A RESTful API to interface with UserVoice's feedback system. Online documentation available here: https://developer.uservoice.com/docs/api/v2/reference/.
 *
 * OpenAPI spec version: 2.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using UserVoiceSdk.Api;
using UserVoiceSdk.Models;
using UserVoiceSdk.Client;
using System.Reflection;

namespace UserVoiceSdk.Test
{
    /// <summary>
    ///  Class for testing Forum
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class ForumTests
    {
        // TODO uncomment below to declare an instance variable for Forum
        //private Forum instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of Forum
            //instance = new Forum();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of Forum
        /// </summary>
        [Test]
        public void ForumInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" Forum
            //Assert.IsInstanceOfType<Forum> (instance, "variable 'instance' is a Forum");
        }

        /// <summary>
        /// Test the property 'CategoryRequired'
        /// </summary>
        [Test]
        public void CategoryRequiredTest()
        {
            // TODO unit test for the property 'CategoryRequired'
        }
        /// <summary>
        /// Test the property 'ClassicVoting'
        /// </summary>
        [Test]
        public void ClassicVotingTest()
        {
            // TODO unit test for the property 'ClassicVoting'
        }
        /// <summary>
        /// Test the property 'CreatedAt'
        /// </summary>
        [Test]
        public void CreatedAtTest()
        {
            // TODO unit test for the property 'CreatedAt'
        }
        /// <summary>
        /// Test the property 'Example'
        /// </summary>
        [Test]
        public void ExampleTest()
        {
            // TODO unit test for the property 'Example'
        }
        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Test]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }
        /// <summary>
        /// Test the property 'IsPrivate'
        /// </summary>
        [Test]
        public void IsPrivateTest()
        {
            // TODO unit test for the property 'IsPrivate'
        }
        /// <summary>
        /// Test the property 'IsPublic'
        /// </summary>
        [Test]
        public void IsPublicTest()
        {
            // TODO unit test for the property 'IsPublic'
        }
        /// <summary>
        /// Test the property 'Links'
        /// </summary>
        [Test]
        public void LinksTest()
        {
            // TODO unit test for the property 'Links'
        }
        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Test]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }
        /// <summary>
        /// Test the property 'OpenSuggestionsCount'
        /// </summary>
        [Test]
        public void OpenSuggestionsCountTest()
        {
            // TODO unit test for the property 'OpenSuggestionsCount'
        }
        /// <summary>
        /// Test the property 'PortalUrl'
        /// </summary>
        [Test]
        public void PortalUrlTest()
        {
            // TODO unit test for the property 'PortalUrl'
        }
        /// <summary>
        /// Test the property 'Prompt'
        /// </summary>
        [Test]
        public void PromptTest()
        {
            // TODO unit test for the property 'Prompt'
        }
        /// <summary>
        /// Test the property 'SuggestionsCount'
        /// </summary>
        [Test]
        public void SuggestionsCountTest()
        {
            // TODO unit test for the property 'SuggestionsCount'
        }
        /// <summary>
        /// Test the property 'UpdatedAt'
        /// </summary>
        [Test]
        public void UpdatedAtTest()
        {
            // TODO unit test for the property 'UpdatedAt'
        }
        /// <summary>
        /// Test the property 'WelcomeMessage'
        /// </summary>
        [Test]
        public void WelcomeMessageTest()
        {
            // TODO unit test for the property 'WelcomeMessage'
        }
        /// <summary>
        /// Test the property 'WelcomeMessageMimeType'
        /// </summary>
        [Test]
        public void WelcomeMessageMimeTypeTest()
        {
            // TODO unit test for the property 'WelcomeMessageMimeType'
        }

    }

}
