/* 
 * UserVoice API
 *
 * A RESTful API to interface with UserVoice's feedback system. Online documentation available here: https://developer.uservoice.com/docs/api/v2/reference/.
 *
 * OpenAPI spec version: 2.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using UserVoiceSdk.Api;
using UserVoiceSdk.Models;
using UserVoiceSdk.Client;
using System.Reflection;

namespace UserVoiceSdk.Test
{
    /// <summary>
    ///  Class for testing Import
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class ImportTests
    {
        // TODO uncomment below to declare an instance variable for Import
        //private Import instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of Import
            //instance = new Import();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of Import
        /// </summary>
        [Test]
        public void ImportInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" Import
            //Assert.IsInstanceOfType<Import> (instance, "variable 'instance' is a Import");
        }

        /// <summary>
        /// Test the property 'CreatedAt'
        /// </summary>
        [Test]
        public void CreatedAtTest()
        {
            // TODO unit test for the property 'CreatedAt'
        }
        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Test]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }
        /// <summary>
        /// Test the property 'ImportCompletedAt'
        /// </summary>
        [Test]
        public void ImportCompletedAtTest()
        {
            // TODO unit test for the property 'ImportCompletedAt'
        }
        /// <summary>
        /// Test the property 'ImportStartedAt'
        /// </summary>
        [Test]
        public void ImportStartedAtTest()
        {
            // TODO unit test for the property 'ImportStartedAt'
        }
        /// <summary>
        /// Test the property 'ImportedRecords'
        /// </summary>
        [Test]
        public void ImportedRecordsTest()
        {
            // TODO unit test for the property 'ImportedRecords'
        }
        /// <summary>
        /// Test the property 'Links'
        /// </summary>
        [Test]
        public void LinksTest()
        {
            // TODO unit test for the property 'Links'
        }
        /// <summary>
        /// Test the property 'ProcessedRows'
        /// </summary>
        [Test]
        public void ProcessedRowsTest()
        {
            // TODO unit test for the property 'ProcessedRows'
        }
        /// <summary>
        /// Test the property 'State'
        /// </summary>
        [Test]
        public void StateTest()
        {
            // TODO unit test for the property 'State'
        }
        /// <summary>
        /// Test the property 'TotalRows'
        /// </summary>
        [Test]
        public void TotalRowsTest()
        {
            // TODO unit test for the property 'TotalRows'
        }
        /// <summary>
        /// Test the property 'Type'
        /// </summary>
        [Test]
        public void TypeTest()
        {
            // TODO unit test for the property 'Type'
        }

    }

}
