/* 
 * UserVoice API
 *
 * A RESTful API to interface with UserVoice's feedback system. Online documentation available here: https://developer.uservoice.com/docs/api/v2/reference/.
 *
 * OpenAPI spec version: 2.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using UserVoiceSdk.Api;
using UserVoiceSdk.Models;
using UserVoiceSdk.Client;
using System.Reflection;

namespace UserVoiceSdk.Test
{
    /// <summary>
    ///  Class for testing Request53
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class Request53Tests
    {
        // TODO uncomment below to declare an instance variable for Request53
        //private Request53 instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of Request53
            //instance = new Request53();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of Request53
        /// </summary>
        [Test]
        public void Request53InstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" Request53
            //Assert.IsInstanceOfType<Request53> (instance, "variable 'instance' is a Request53");
        }

        /// <summary>
        /// Test the property 'Includes'
        /// </summary>
        [Test]
        public void IncludesTest()
        {
            // TODO unit test for the property 'Includes'
        }
        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Test]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }
        /// <summary>
        /// Test the property '_Params'
        /// </summary>
        [Test]
        public void _ParamsTest()
        {
            // TODO unit test for the property '_Params'
        }
        /// <summary>
        /// Test the property 'Position'
        /// </summary>
        [Test]
        public void PositionTest()
        {
            // TODO unit test for the property 'Position'
        }
        /// <summary>
        /// Test the property 'Subscribed'
        /// </summary>
        [Test]
        public void SubscribedTest()
        {
            // TODO unit test for the property 'Subscribed'
        }
        /// <summary>
        /// Test the property 'SubscriptionParams'
        /// </summary>
        [Test]
        public void SubscriptionParamsTest()
        {
            // TODO unit test for the property 'SubscriptionParams'
        }

    }

}
