/* 
 * UserVoice API
 *
 * A RESTful API to interface with UserVoice's feedback system. Online documentation available here: https://developer.uservoice.com/docs/api/v2/reference/.
 *
 * OpenAPI spec version: 2.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using UserVoiceSdk.Api;
using UserVoiceSdk.Models;
using UserVoiceSdk.Client;
using System.Reflection;

namespace UserVoiceSdk.Test
{
    /// <summary>
    ///  Class for testing Request41
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class Request41Tests
    {
        // TODO uncomment below to declare an instance variable for Request41
        //private Request41 instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of Request41
            //instance = new Request41();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of Request41
        /// </summary>
        [Test]
        public void Request41InstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" Request41
            //Assert.IsInstanceOfType<Request41> (instance, "variable 'instance' is a Request41");
        }

        /// <summary>
        /// Test the property 'AttachmentTokens'
        /// </summary>
        [Test]
        public void AttachmentTokensTest()
        {
            // TODO unit test for the property 'AttachmentTokens'
        }
        /// <summary>
        /// Test the property 'Body'
        /// </summary>
        [Test]
        public void BodyTest()
        {
            // TODO unit test for the property 'Body'
        }
        /// <summary>
        /// Test the property 'BodyMimeType'
        /// </summary>
        [Test]
        public void BodyMimeTypeTest()
        {
            // TODO unit test for the property 'BodyMimeType'
        }
        /// <summary>
        /// Test the property 'CategoryName'
        /// </summary>
        [Test]
        public void CategoryNameTest()
        {
            // TODO unit test for the property 'CategoryName'
        }
        /// <summary>
        /// Test the property 'CreatedAt'
        /// </summary>
        [Test]
        public void CreatedAtTest()
        {
            // TODO unit test for the property 'CreatedAt'
        }
        /// <summary>
        /// Test the property 'ForumName'
        /// </summary>
        [Test]
        public void ForumNameTest()
        {
            // TODO unit test for the property 'ForumName'
        }
        /// <summary>
        /// Test the property 'Includes'
        /// </summary>
        [Test]
        public void IncludesTest()
        {
            // TODO unit test for the property 'Includes'
        }
        /// <summary>
        /// Test the property 'Labels'
        /// </summary>
        [Test]
        public void LabelsTest()
        {
            // TODO unit test for the property 'Labels'
        }
        /// <summary>
        /// Test the property 'Links'
        /// </summary>
        [Test]
        public void LinksTest()
        {
            // TODO unit test for the property 'Links'
        }
        /// <summary>
        /// Test the property 'State'
        /// </summary>
        [Test]
        public void StateTest()
        {
            // TODO unit test for the property 'State'
        }
        /// <summary>
        /// Test the property 'StatusName'
        /// </summary>
        [Test]
        public void StatusNameTest()
        {
            // TODO unit test for the property 'StatusName'
        }
        /// <summary>
        /// Test the property 'StatusUpdateBody'
        /// </summary>
        [Test]
        public void StatusUpdateBodyTest()
        {
            // TODO unit test for the property 'StatusUpdateBody'
        }
        /// <summary>
        /// Test the property 'StatusUpdateCreatedAt'
        /// </summary>
        [Test]
        public void StatusUpdateCreatedAtTest()
        {
            // TODO unit test for the property 'StatusUpdateCreatedAt'
        }
        /// <summary>
        /// Test the property 'StatusUpdateCreatedByEmail'
        /// </summary>
        [Test]
        public void StatusUpdateCreatedByEmailTest()
        {
            // TODO unit test for the property 'StatusUpdateCreatedByEmail'
        }
        /// <summary>
        /// Test the property 'Title'
        /// </summary>
        [Test]
        public void TitleTest()
        {
            // TODO unit test for the property 'Title'
        }
        /// <summary>
        /// Test the property 'UserEmail'
        /// </summary>
        [Test]
        public void UserEmailTest()
        {
            // TODO unit test for the property 'UserEmail'
        }
        /// <summary>
        /// Test the property 'UserName'
        /// </summary>
        [Test]
        public void UserNameTest()
        {
            // TODO unit test for the property 'UserName'
        }

    }

}
