/* 
 * UserVoice API
 *
 * A RESTful API to interface with UserVoice's feedback system. Online documentation available here: https://developer.uservoice.com/docs/api/v2/reference/.
 *
 * OpenAPI spec version: 2.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using UserVoiceSdk.Api;
using UserVoiceSdk.Models;
using UserVoiceSdk.Client;
using System.Reflection;

namespace UserVoiceSdk.Test
{
    /// <summary>
    ///  Class for testing Request40
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class Request40Tests
    {
        // TODO uncomment below to declare an instance variable for Request40
        //private Request40 instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of Request40
            //instance = new Request40();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of Request40
        /// </summary>
        [Test]
        public void Request40InstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" Request40
            //Assert.IsInstanceOfType<Request40> (instance, "variable 'instance' is a Request40");
        }

        /// <summary>
        /// Test the property 'AttachmentTokens'
        /// </summary>
        [Test]
        public void AttachmentTokensTest()
        {
            // TODO unit test for the property 'AttachmentTokens'
        }
        /// <summary>
        /// Test the property 'Body'
        /// </summary>
        [Test]
        public void BodyTest()
        {
            // TODO unit test for the property 'Body'
        }
        /// <summary>
        /// Test the property 'BodyMimeType'
        /// </summary>
        [Test]
        public void BodyMimeTypeTest()
        {
            // TODO unit test for the property 'BodyMimeType'
        }
        /// <summary>
        /// Test the property 'CreatedAt'
        /// </summary>
        [Test]
        public void CreatedAtTest()
        {
            // TODO unit test for the property 'CreatedAt'
        }
        /// <summary>
        /// Test the property 'Includes'
        /// </summary>
        [Test]
        public void IncludesTest()
        {
            // TODO unit test for the property 'Includes'
        }
        /// <summary>
        /// Test the property 'Links'
        /// </summary>
        [Test]
        public void LinksTest()
        {
            // TODO unit test for the property 'Links'
        }
        /// <summary>
        /// Test the property 'Title'
        /// </summary>
        [Test]
        public void TitleTest()
        {
            // TODO unit test for the property 'Title'
        }

    }

}
