/* 
 * UserVoice API
 *
 * A RESTful API to interface with UserVoice's feedback system. Online documentation available here: https://developer.uservoice.com/docs/api/v2/reference/.
 *
 * OpenAPI spec version: 2.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using UserVoiceSdk.Api;
using UserVoiceSdk.Models;
using UserVoiceSdk.Client;
using System.Reflection;

namespace UserVoiceSdk.Test
{
    /// <summary>
    ///  Class for testing SuggestionLinks
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class SuggestionLinksTests
    {
        // TODO uncomment below to declare an instance variable for SuggestionLinks
        //private SuggestionLinks instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of SuggestionLinks
            //instance = new SuggestionLinks();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of SuggestionLinks
        /// </summary>
        [Test]
        public void SuggestionLinksInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" SuggestionLinks
            //Assert.IsInstanceOfType<SuggestionLinks> (instance, "variable 'instance' is a SuggestionLinks");
        }

        /// <summary>
        /// Test the property 'Category'
        /// </summary>
        [Test]
        public void CategoryTest()
        {
            // TODO unit test for the property 'Category'
        }
        /// <summary>
        /// Test the property 'CreatedBy'
        /// </summary>
        [Test]
        public void CreatedByTest()
        {
            // TODO unit test for the property 'CreatedBy'
        }
        /// <summary>
        /// Test the property 'Forum'
        /// </summary>
        [Test]
        public void ForumTest()
        {
            // TODO unit test for the property 'Forum'
        }
        /// <summary>
        /// Test the property 'Labels'
        /// </summary>
        [Test]
        public void LabelsTest()
        {
            // TODO unit test for the property 'Labels'
        }
        /// <summary>
        /// Test the property 'LastStatusUpdate'
        /// </summary>
        [Test]
        public void LastStatusUpdateTest()
        {
            // TODO unit test for the property 'LastStatusUpdate'
        }
        /// <summary>
        /// Test the property 'ParentSuggestion'
        /// </summary>
        [Test]
        public void ParentSuggestionTest()
        {
            // TODO unit test for the property 'ParentSuggestion'
        }
        /// <summary>
        /// Test the property 'ParentSuggestions'
        /// </summary>
        [Test]
        public void ParentSuggestionsTest()
        {
            // TODO unit test for the property 'ParentSuggestions'
        }
        /// <summary>
        /// Test the property 'Status'
        /// </summary>
        [Test]
        public void StatusTest()
        {
            // TODO unit test for the property 'Status'
        }
        /// <summary>
        /// Test the property 'Ticket'
        /// </summary>
        [Test]
        public void TicketTest()
        {
            // TODO unit test for the property 'Ticket'
        }

    }

}
